### PR TITLE
Add parallel build support

### PR DESCRIPTION
**Pull request by loicfm**
I've observed drastic improvement by adding -j <number> to cmake build.
I went from almost 40 min (using WSL 2) to less than 5min.

### CODE REVIEW

**Comment by Mause** [comment]
Generally we recommend using the Ninja generator instead of setting the parallelism directly, as Ninja is much faster than make

**Comment by loicfm** [comment]
Thank you @Mause for highlighting this!
I've followed all the steps available at [duckdb/extension-template](https://github.com/duckdb/extension-template). Is there anything that I am missing?

**Comment by szarnyasg** [comment]
@loicfm The recommendation for Ninja is in the [Building](https://duckdb.org/dev/building#prerequisites) page of the docs.

**Comment by loicfm** [comment]
@szarnyasg I've checked [Building](https://duckdb.org/dev/building#prerequisites) page of the docs and I confirm that _-j 4_ is not required.
Maybe the [README](https://github.com/duckdb/extension-template/blob/e1ea71368c665b0a3931c01364df70dccab25728/docs/README.md) needs to highlight this?

**Pull request closed without merging**
